# Generated by Django 5.1.4 on 2025-05-03 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_type_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField()),
                ('score', models.FloatField()),
                ('remarks', models.CharField(max_length=255)),
                ('attempts', models.IntegerField()),
            ],
        ),
    ]
