# Generated by Django 5.1.4 on 2025-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userlog',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlog',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='remarks',
            field=models.CharField(max_length=100),
        ),
    ]
