# Generated by Django 5.1.4 on 2025-05-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userlog_user_id_userlog_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='game_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
